# Limpeza do arquivo train.csv

In [8]:
import pandas as pd
import datetime

# criar o dataframe
df = pd.read_csv('train.csv')
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45588,0x7c09,JAPRES04DEL01,30,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35:00,11:45:00,conditions Windy,High,1,Meal,motorcycle,0,No,Metropolitian,(min) 32
45589,0xd641,AGRRES16DEL01,21,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55:00,20:10:00,conditions Windy,Jam,0,Buffet,motorcycle,1,No,Metropolitian,(min) 36
45590,0x4f8d,CHENRES08DEL03,30,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50:00,00:05:00,conditions Cloudy,Low,1,Drinks,scooter,0,No,Metropolitian,(min) 16
45591,0x5eee,COIMBRES11DEL01,20,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35:00,13:40:00,conditions Cloudy,High,0,Snack,motorcycle,1,No,Metropolitian,(min) 26
45592,0x5fb2,RANCHIRES09DEL02,23,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10:00,17:15:00,conditions Fog,Medium,2,Snack,scooter,1,No,Metropolitian,(min) 36

In [9]:
df.dtypes # Mostra os tipos de dados de cada coluna
            # object = texto / string

ID                              object
Delivery_person_ID              object
Delivery_person_Age             object
Delivery_person_Ratings         object
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Weatherconditions               object
Road_traffic_density            object
Vehicle_condition                int64
Type_of_order                   object
Type_of_vehicle                 object
multiple_deliveries             object
Festival                        object
City                            object
Time_taken(min)                 object
dtype: object

## Retira linhas com 'NaN'

In [10]:

# seleciona apenas linhas que não tem 'NaN ' na coluna de idade, avalização, multiple_deliveries, densidade de tráfego, condição climatica e Cidade
linhas_com_valor = (df['Delivery_person_Age'] != 'NaN ') & (df['Delivery_person_Ratings'] != 'NaN ') & (df['multiple_deliveries'] != 'NaN ')
# Deixa apenas as linhas que não tem 'NaN ' em nenhuma das colunas citadas acima
df = df.loc[linhas_com_valor, :]

# seleciona apenas linhas que não tem 'NaN ' na coluna de idade, avalização, multiple_deliveries, densidade de tráfego, condição climatica e Cidade
linhas_com_valor = (df['Road_traffic_density'] != 'NaN ') & (df['Weatherconditions'] != 'conditions NaN') & (df['City'] != 'NaN ') & (df['Festival'] != 'NaN ')
# Deixa apenas as linhas que não tem 'NaN ' em nenhuma das colunas citadas acima
df = df.loc[linhas_com_valor, :]

## Converte o tipo de algumas colunas que está errado

In [11]:
# Conversões:
df['Delivery_person_Age'] = df['Delivery_person_Age'].astype(int) # converte a coluna de idade de object para inteiro

df['Delivery_person_Ratings'] = df['Delivery_person_Ratings'].astype(float) # muda o tipo da coluna Delivery_person_Ratings que está como Object e deve ser Float

# Usa a biblioteca datetime, importada na primeira célula
df['Order_Date'] = pd.to_datetime( df['Order_Date'], format='%d-%m-%Y' ) # Corrigindo a coluna Order_Date. Para mudar para data é diferente, precisamos importar ima biblioteca

df['multiple_deliveries'] = df['multiple_deliveries'].astype(int) # converte a coluna para inteiro

df['Time_taken(min)'] = df['Time_taken(min)'].str.replace('(min) ', '').astype(int) # Retira parte da string ('(mim)') e converte para inteiro

df['Weatherconditions'] = df['Weatherconditions'].str.replace('conditions ', '')

df.dtypes

ID                                     object
Delivery_person_ID                     object
Delivery_person_Age                     int64
Delivery_person_Ratings               float64
Restaurant_latitude                   float64
Restaurant_longitude                  float64
Delivery_location_latitude            float64
Delivery_location_longitude           float64
Order_Date                     datetime64[ns]
Time_Orderd                            object
Time_Order_picked                      object
Weatherconditions                      object
Road_traffic_density                   object
Vehicle_condition                       int64
Type_of_order                          object
Type_of_vehicle                        object
multiple_deliveries                     int64
Festival                               object
City                                   object
Time_taken(min)                         int64
dtype: object

## Reseta o index do DF

In [12]:
# como excluímos linhas que continham NaN, o index do nosso df ficou com "buracos" (se fizer um df.head(20) na célula a cima, verá que não há index 17)
# os index das linhas excluídas foram excluídos junto

# Devido a isso temos que resetar o index do df para que fique na sequência correta
df = df.reset_index(drop=True) # O drop é necesário pois sem ele o reset cria uma coluna com os index antigos
df.head(20)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,11:30:00,11:45:00,Sunny,High,2,Snack,motorcycle,0,No,Urban,24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,19:45:00,19:50:00,Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,08:30:00,08:45:00,Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,18:00:00,18:10:00,Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,13:30:00,13:45:00,Cloudy,High,1,Snack,scooter,1,No,Metropolitian,30
5,0x9bb4,HYDRES09DEL03,22,4.8,17.431668,78.408321,17.461668,78.438321,2022-03-11,21:20:00,21:30:00,Cloudy,Jam,0,Buffet,motorcycle,1,No,Urban,26
6,0x95b4,RANCHIRES15DEL01,33,4.7,23.369746,85.339820,23.479746,85.449820,2022-03-04,19:15:00,19:30:00,Fog,Jam,1,Meal,scooter,1,No,Metropolitian,40
7,0x9eb2,MYSRES15DEL02,35,4.6,12.352058,76.606650,12.482058,76.736650,2022-03-14,17:25:00,17:30:00,Cloudy,Medium,2,Meal,motorcycle,1,No,Metropolitian,32
8,0x1102,HYDRES05DEL02,22,4.8,17.433809,78.386744,17.563809,78.516744,2022-03-20,20:55:00,21:05:00,Stormy,Jam,0,Buffet,motorcycle,1,No,Metropolitian,34
9,0xcdcd,DEHRES17DEL01,36,4.2,30.327968,78.046106,30.397968,78.116106,2022-02-12,21:55:00,22:10:00,Fog,Jam,2,Snack,motorcycle,3,No,Metropolitian,46
10,0xd987,KOCRES16DEL01,21,4.7,10.003064,76.307589,10.043064,76.347589,2022-02-13,14:55:00,15:05:00,Stormy,High,1,Meal,motorcycle,1,No,Metropolitian,23
11,0x2784,PUNERES13DEL03,23,4.7,18.562450,73.916619,18.652450,74.006619,2022-03-04,17:30:00,17:40:00,Sandstorms,Medium,1,Drinks,scooter,1,No,Metropolitian,21
12,0xc8b6,LUDHRES15DEL02,34,4.3,30.899584,75.809346,30.919584,75.829346,2022-02-13,09:20:00,09:30:00,Sandstorms,Low,0,Buffet,motorcycle,0,No,Metropolitian,20
13,0xdb64,KNPRES14DEL02,24,4.7,26.463504,80.372929,26.593504,80.502929,2022-02-14,19:50:00,20:05:00,Fog,Jam,1,Snack,scooter,1,No,Metropolitian,41
14,0x3af3,MUMRES15DEL03,29,4.5,19.176269,72.836721,19.266269,72.926721,2022-04-02,20:25:00,20:35:00,Sandstorms,Jam,2,Buffet,electric_scooter,1,No,Metropolitian,20
15,0x3aab,MYSRES01DEL01,35,4.0,12.311072,76.654878,12.351072,76.694878,2022-03-01,14:55:00,15:10:00,Windy,High,1,Meal,scooter,1,No,Metropolitian,33
16,0x689b,PUNERES20DEL01,33,4.2,18.592718,73.773572,18.702718,73.883572,2022-03-16,20:30:00,20:40:00,Sandstorms,Jam,2,Snack,motorcycle,1,No,Metropolitian,40
17,0xc9cf,KOLRES15DEL03,21,4.7,22.552672,88.352885,22.582672,88.382885,2022-02-15,21:15:00,21:30:00,Windy,Jam,0,Meal,motorcycle,1,No,Urban,15
18,0x36b8,PUNERES19DEL02,25,4.1,18.563934,73.915367,18.643935,73.995367,2022-03-16,20:20:00,20:25:00,Sandstorms,Jam,0,Snack,motorcycle,2,No,Metropolitian,36
19,0x5795,RANCHIRES06DEL02,31,4.7,23.357804,85.325146,23.487804,85.455146,2022-03-10,22:30:00,22:45:00,Sandstorms,Low,2,Meal,electric_scooter,0,No,Metropolitian,26

## Retira todos os espaços desnecessários em colunas do tipo "object"

In [13]:
# Como podemos observar nesse comando, as str dessa tabela apresentam um espaço no fim, oque não é bom!
# Vamos excluir esses espaços das str
df.iloc[0,0]

'0x4607 '

In [14]:
# para excluir espaços usamos o strip()
print(df.iloc[0,0].strip())

# porém precisamos fazer isso em todas as colunas
# usamos FOR para percorrer todas as colunas do tipo Object
for a in [0, 1, 9, 10, 11, 12, 14, 15, 17, 18]:
  df.iloc[:, a] = df.iloc[:, a].str.strip() # Mais rápido que fazer outro FOR

print('Espaços desnecessários excluídos!!!')
  # OU
  #for b in range(0, df.shape[0]):
    #df.iloc[b, a] = df.iloc[b, a].strip()

0x4607
Espaços desnecessários excluídos!!!

## Cria uma nova coluna, que mostra a distância entre o restaurante e o local de entrega

In [30]:
# Instala a biblioteca usada na célula a baixo, para criar a coluna distância.
!pip show geopy

#!pip install geopy

Name: geopy
Version: 2.4.1
Summary: Python Geocoding Toolbox
Home-page: https://github.com/geopy/geopy
Author:
Author-email:
License: MIT
Location: C:\Users\gabriel.ganassin\AppData\Roaming\jupyterlab-desktop\jlab_server\Lib\site-packages
Requires: geographiclib
Required-by:

In [15]:
# Adicionando uma nova coluna, que mostra a distância entre o restaurante e o local de entrega
from geopy.distance import great_circle

# Função para calcular a distância usando great_circle
def calcular_distancia(row):
    coord_restaurante = (row['Restaurant_latitude'], row['Restaurant_longitude'])
    coord_entrega = (row['Delivery_location_latitude'], row['Delivery_location_longitude'])
    return great_circle(coord_restaurante, coord_entrega).kilometers

# Aplicar a função ao DataFrame
df['distancia_km'] = df.apply(calcular_distancia, axis=1)

# Exibir o DataFrame com a distância calculada (última coluna)
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min),distancia_km
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,11:30:00,...,Sunny,High,2,Snack,motorcycle,0,No,Urban,24,3.025154
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,19:45:00,...,Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,33,20.183558
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,08:30:00,...,Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,26,1.552760
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,18:00:00,...,Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,21,7.790412
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,13:30:00,...,Cloudy,High,1,Snack,scooter,1,No,Metropolitian,30,6.210147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41363,0x7c09,JAPRES04DEL01,30,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,11:35:00,...,Windy,High,1,Meal,motorcycle,0,No,Metropolitian,32,1.489848
41364,0xd641,AGRRES16DEL01,21,4.6,0.000000,0.000000,0.070000,0.070000,2022-02-16,19:55:00,...,Windy,Jam,0,Buffet,motorcycle,1,No,Metropolitian,36,11.007750
41365,0x4f8d,CHENRES08DEL03,30,4.9,13.022394,80.242439,13.052394,80.272439,2022-03-11,23:50:00,...,Cloudy,Low,1,Drinks,scooter,0,No,Metropolitian,16,4.657202
41366,0x5eee,COIMBRES11DEL01,20,4.7,11.001753,76.986241,11.041753,77.026241,2022-03-07,13:35:00,...,Cloudy,High,0,Snack,motorcycle,1,No,Metropolitian,26,6.232402
41367,0x5fb2,RANCHIRES09DEL02,23,4.9,23.351058,85.325731,23.431058,85.405731,2022-03-02,17:10:00,...,Fog,Medium,2,Snack,scooter,1,No,Metropolitian,36,12.074413

## Salva o df limpo em um novo arquivo .csv

In [16]:

df.to_csv('train_limpo.csv', index=False)